config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :users
    resources :admin_users
    resources :posts
    resources :employees
    
    root to: "users#index"
  end
  
  resources :audit_logs, except: %i[:new :edit :destroy] do
    member do
      get :confirm
    end
  end
  
  resources :posts do
    member do
      get :approve
    end
  end
  
  devise_for :users, skip: [:registrations]
  root to: 'static#homepage'
end

app/views/shared/_audit_log_tab.html.erb
<li class="nav-item">
  <div class="nav-link <%= active?(audit_logs_path) %>">
    <%= link_to "Audit Log", audit_logs_path %>
  </div>
</li>

app/views/shared/_nav.html.erb
<div class="logo text-center">
  <h1>Time Tracker</h1>
</div>

<!--TODO-->
<% if current_user %>
  <ul class="custom-nav nav nav-tabs mb-lg-4">
    <li class="nav-item">
      <div class="nav-link <%= active?(root_path) %>">
        <%= link_to "Home", root_path %>
      </div>
    </li>
    <li class="nav-item">
      <div class="nav-link <%= active?(posts_path) %>">
        <%= link_to "Time Entries", posts_path %>
      </div>
    </li>

    <%= render 'shared/audit_log_tab' if policy(AuditLog).index? %>

    <li class="nav-item">
      <div class="nav-link <%= active?(new_post_path) %>">
        <%= link_to "Request Overtime", new_post_path, id: 'new_post_from_nav' %>
      </div>
    </li>
    <li class="nav-item dropdown ml-md-auto">
      <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Options</a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
        <!--TODO-->
        <% if current_user.try(:type) == 'AdminUser' %>
          <%= link_to "Admin dash bord", admin_root_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
        <% end %>
        <!--TODO-->
        <%= link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" }, class: "dropdown-item" %>
      </div>
    </li>
  </ul>
<% end %>
<!--TODO-->

app/views/shared/_toaster_flash.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
      <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'success').gsub('info', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>');
      <% end %>
  </script>
<% end %>